django_e_commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("e_commerce/", include("e_commerce.urls")),
    path('admin/', admin.site.urls),
]

e_commerce/urls.py
from django.urls import path

from . import views

app_name = "e_commerce"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/achat", views.achat, name="achat"),
    path("<int:pk>/retour", views.enleverProduit, name="enleverProduit"),
    path("connexion/", views.connexion, name="connexion"),
    path("inscription/", views.inscription, name="inscription"),
    path("panier/", views.panier, name="panier"),
    path("deconnexion/", views.logout_view, name="logout_view"),
]

e_commerce/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import User

class Produit(models.Model):
    contenu = models.CharField(max_length=200)
    prix = models.IntegerField(default=0)
    titre = models.CharField(max_length=100)

class Panier(models.Model):
    produit = models.ForeignKey(Produit, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

e_commerce/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3 mt-2'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-3 mt-2'}))

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3 mt-2'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-3 mt-2'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-3 mt-2'}), label='Confirmer le mot de passe')

e_commerce/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .models import Panier, Produit
from .forms import LoginForm
from .forms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.models import User

def index(request):
    data = Produit.objects.all()
    produit = {'produit': data}
    return render(request, "e_commerce/index.html", produit)
def connexion(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/e_commerce/')
        else:
            form = LoginForm()
            error_message = 'Identifiants invalides'
            context = {'form': form, 'error_message': error_message}
            return render(request, "e_commerce/connexion.html", context)
    else:
        form = LoginForm()
        context = {'form': form}
        return render(request, 'e_commerce/connexion.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/e_commerce/')

def inscription(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            User.objects.create_user(username=username, password=password)
            return HttpResponseRedirect('/e_commerce/connexion/')
        else:
            form = RegisterForm()
            error_message = 'Identifiants invalides'
            context = {'form': form, 'error_message': error_message}
            return render(request, "e_commerce/inscription.html", context)
    else:
        form = RegisterForm()
        context = {'form': form}
        return render(request, "e_commerce/inscription.html", context)

def panier(request):
    data = Panier.objects.filter(user_id=request.user.id).order_by('produit_id')
    total = 0
    for i in data:
        total += i.produit.prix
    context = {'panier': data,
               'total': total}
    return render(request, "e_commerce/panier.html", context)

def achat(request, pk):
    Panier.objects.create(produit_id=pk, user_id=request.user.id)
    return HttpResponseRedirect('/e_commerce/')

def enleverProduit(request, pk):
    data = Panier.objects.filter(id=pk)
    data.delete()
    return HttpResponseRedirect('/e_commerce/panier/')

e_commerce/templates/e_commerce/connexion.html
{% extends 'e_commerce/menu.html' %}
{% block content %}
<body>
    <h1>Vous connecter</h1>
    <p>Veuilllez compléter le formulaire pour vous connecter:</p>
        <form method="POST">
            {% csrf_token %}
            {% if error_message %}
                <p>{{ error_message }}</p>
            {% endif %}
            {{ form.as_p }}
            <button class="btn btn-dark" type="submit">connexion</button>
        </form>
    <hr>
    <h1>Vous inscrire</h1>
    <p>Cliquer sur le bouton suivant pour aller a la page d'inscription:</p>
    <button class="btn btn-dark"><a class="noLink" href="{% url 'e_commerce:inscription' %}">inscription</a></button>
</body>
{% endblock %}

e_commerce/templates/e_commerce/index.html
{% extends 'e_commerce/menu.html' %}
{% block content %}
    <body>
        <div class="row">
            <h1>Catalogue</h1>
            {% for produits in produit %}
                <article class="col-4 mb-4">
                    <div class="card">
                        <h2 class="card-header">
                            {{ produits.titre }}
                        </h2>
                        <div class="card-body article_contenu">
                            {{ produits.contenu }}
                        </div>
                        <footer class="card-footer d-flex justify-content-between">
                            {% if user.is_authenticated %}
                                <a href="{% url 'e_commerce:achat' produits.id %}" class="btn btn-dark">Ajouter au panier</a>
                            {% else %}
                                <p>Connecter vous pour pouvoir acheter</p>
                            {% endif %}
                            <h5 class="mt-2">{{ produits.prix }} €</h5>
                        </footer>
                    </div>
                </article>
            {% endfor %}
        </div>
    </body>
{% endblock %}

e_commerce/templates/e_commerce/inscription.html
{% extends 'e_commerce/menu.html' %}
{% block content %}
    <body>
        <h1>Vous inscrire</h1>
        <p>Veuilllez compléter le formulaire pour vous inscrire:</p>
        <form method="POST">
            {% csrf_token %}
            {% if error_message %}
                <p>{{ error_message }}</p>
            {% endif %}
            {{ form.as_p }}
            <button class="btn btn-dark" type="submit">connexion</button>
        </form>
    </body>
{% endblock %}

e_commerce/templates/e_commerce/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'e_commerce/e_commerce.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <div class="bg-dark display-table">
        <nav class="navbar navbar-expand navbar-dark container">
        <span class="navbar-brand fs-3">
            <h5>Mini E commerce</h5>
        </span>
            <ul class="navbar-nav">
                <li class="nav-item mx-3">
                    <a href="{% url 'e_commerce:index' %}">Produit</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'e_commerce:panier' %}">Panier</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                <li class="navbar-item ">
                    <a href="{% url 'e_commerce:logout_view' %}">Déconnexion</a>
                </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="navbar-item ">
                        <a href="{% url 'e_commerce:connexion' %}">Connexion</a>
                    </li>
                </ul>
            {% endif %}
        </nav>
    </div>
</head>
<div class="px-3">
    {% block content %}{% endblock %}
</div>
</html>

e_commerce/templates/e_commerce/panier.html
{% extends 'e_commerce/menu.html' %}
{% block content %}
    <body>
        <div class="d-flex justify-content-between align-items-center mb-3">
                </div>
                <table class="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>nom</th>
                            <th>prix</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for paniers in panier %}
                            <tr>
                                <td>{{ paniers.produit.id }}</td>
                                <td>{{ paniers.produit.titre }}</td>
                                <td>{{ paniers.produit.prix }} €</td>
                                <td>
                                    <a href="{% url 'e_commerce:enleverProduit' paniers.id %}" class="btn btn-danger">supprimer</a>
                                </td>
                            </tr>
                    {% endfor %}
                    </tbody>
                </table>
    <h3>Total = {{ total }} €</h3>
    </body>
{% endblock %}